const cfg=window.HERO_CONFIG||{};
const ready=cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.includes('YOUR-PROJECT')&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes('YOUR-SUPABASE');
const db=ready?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function errMsg(e){return e?.message||'Terjadi kesalahan.'}
async function upload(file,bucket='hero-images',folder='uploads'){if(!file)return '';const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${folder}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return path;}
async function init(){
 if(!ready){$('#loginMsg').textContent='Konfigurasi Supabase belum diisi. Buka admin/js/config.js.';return;}
 const {data:{session}}=await db.auth.getSession(); show(session);
 db.auth.onAuthStateChange((_e,s)=>show(s));
}
function show(session){$('#loginView').hidden=!!session;$('#appView').hidden=!session;if(session){loadAll();}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginMsg').textContent='';const {error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)$('#loginMsg').textContent=errMsg(error)});
$('#logout').onclick=async()=>{await db.auth.signOut()};
$$('#tabs button').forEach(b=>b.onclick=()=>{ $$('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab').forEach(x=>x.classList.remove('active'));$('#tab-'+b.dataset.tab).classList.add('active');$('#pageTitle').textContent='Dashboard '+(b.textContent.replace(/^\S+\s/,'')||'');});
async function loadAll(){loadHome();loadStructures();loadCourses();loadMembers();loadEvents();loadMemories();loadCorner();}
async function loadHome(){const {data,error}=await db.from('site_content').select('key,value');if(error)return toast(errMsg(error));const o=Object.fromEntries((data||[]).map(x=>[x.key,x.value]));['home_eyebrow','home_title','home_lead','announcement_title','announcement_date','announcement_text','announcement_time'].forEach(k=>$('#'+k).value=o[k]||'');}
$('#saveHome').onclick=async()=>{const keys=['home_eyebrow','home_title','home_lead','announcement_title','announcement_date','announcement_text','announcement_time'];const rows=keys.map(key=>({key,value:$('#'+key).value,updated_at:new Date().toISOString()}));const {error}=await db.from('site_content').upsert(rows);if(error)return toast(errMsg(error));toast('Home berhasil disimpan');};
async function loadStructures(){const {data}=await db.from('structure').select('*').order('position');const box=$('#structureList');box.innerHTML=(data||[]).map(x=>`<div class="row"><input type="number" data-k="position" value="${x.position}" data-id="${x.id}"><label>Jabatan<input data-k="role" value="${esc(x.role)}" data-id="${x.id}"></label><label>Nama<input data-k="name" value="${esc(x.name)}" data-id="${x.id}"></label><label>NIM<input data-k="nim" value="${esc(x.nim||'')}" data-id="${x.id}"></label><label>Foto<input type="file" accept="image/*" data-photo>${x.photo_path?`<img class="preview" src="${esc(db.storage.from('class-photos').getPublicUrl(x.photo_path).data.publicUrl)}">`:''}</label><div class="actions"><button class="edit" onclick="saveClassRow('structure','${x.id}',this)">Simpan</button><button class="delete" onclick="removeRow('structure','${x.id}',loadStructures)">Hapus</button></div></div>`).join('')||'<p>Belum ada struktur kelas.</p>';}
$('#addStructure').onclick=async()=>{const {error}=await db.from('structure').insert({position:99,role:'JABATAN BARU',name:'Nama',nim:''});if(error)toast(errMsg(error));else loadStructures();};
async function loadCourses(){const {data}=await db.from('courses').select('*').order('position');const box=$('#courseList');box.innerHTML=(data||[]).map(x=>`<div class="row"><input type="number" data-k="position" value="${x.position}" data-id="${x.id}"><label>Mata Kuliah<input data-k="name" value="${esc(x.name)}" data-id="${x.id}"></label><label>PJ<input data-k="pj" value="${esc(x.pj||'')}" data-id="${x.id}"></label><label>Foto PJ<input type="file" accept="image/*" data-photo>${x.photo_path?`<img class="preview" src="${esc(db.storage.from('class-photos').getPublicUrl(x.photo_path).data.publicUrl)}">`:''}</label><div class="actions"><button class="edit" onclick="saveClassRow('courses','${x.id}',this)">Simpan</button><button class="delete" onclick="removeRow('courses','${x.id}',loadCourses)">Hapus</button></div></div>`).join('')||'<p>Belum ada mata kuliah.</p>';}
$('#addCourse').onclick=async()=>{const {error}=await db.from('courses').insert({position:99,name:'Mata Kuliah Baru',pj:'Nama PJ'});if(error)toast(errMsg(error));else loadCourses();};
async function loadMembers(){const {data}=await db.from('members').select('*').order('position');const box=$('#memberList');if(!box)return;box.innerHTML=(data||[]).map(x=>`<div class="row"><input type="number" data-k="position" value="${x.position}"><label>Nama<input data-k="name" value="${esc(x.name)}"></label><label>NIM<input data-k="nim" value="${esc(x.nim||'')}"></label><label>Foto<input type="file" accept="image/*" data-photo>${x.photo_path?`<img class="preview" src="${esc(db.storage.from('class-photos').getPublicUrl(x.photo_path).data.publicUrl)}">`:''}</label><div class="actions"><button class="edit" onclick="saveClassRow('members','${x.id}',this)">Simpan</button><button class="delete" onclick="removeRow('members','${x.id}',loadMembers)">Hapus</button></div></div>`).join('')||'<p>Belum ada anggota. Klik Tambah.</p>';}
$('#addMember').onclick=async()=>{const {error}=await db.from('members').insert({position:99,name:'Anggota Baru',nim:''});if(error)toast(errMsg(error));else loadMembers();};
async function saveClassRow(table,id,btn){try{const row=btn.closest('.row'),vals={};row.querySelectorAll('[data-k]').forEach(i=>vals[i.dataset.k]=i.value);vals.position=Number(vals.position)||99;const f=row.querySelector('[data-photo]')?.files?.[0];if(f) vals.photo_path=await upload(f,'class-photos',table);const {error}=await db.from(table).update(vals).eq('id',id);if(error)throw error;toast('Disimpan');table==='structure'?loadStructures():table==='courses'?loadCourses():loadMembers();}catch(e){toast(errMsg(e));}}
window.saveRow=async(table,id,btn)=>{const row=btn.closest('.row');const vals={};row.querySelectorAll('[data-k]').forEach(i=>vals[i.dataset.k]=i.value);vals.position=Number(vals.position)||99;const {error}=await db.from(table).update(vals).eq('id',id);if(error)toast(errMsg(error));else toast('Disimpan');};
window.removeRow=async(table,id,fn)=>{if(!confirm('Hapus data ini?'))return;const {error}=await db.from(table).delete().eq('id',id);if(error)toast(errMsg(error));else fn();};
async function loadEvents(){const {data}=await db.from('events').select('*').order('position');const box=$('#eventList');box.innerHTML=(data||[]).map(x=>editorEvent(x)).join('')||'<p>Belum ada event.</p>';}
function editorEvent(x){return `<div class="card-editor"><label>Tanggal<input data-field="event_date" value="${esc(x.event_date)}"></label><label>Judul<input data-field="title" value="${esc(x.title)}"></label><label>Waktu / Lokasi<input data-field="time_location" value="${esc(x.time_location||'')}"></label><label>Urutan<input type="number" data-field="position" value="${x.position}"></label><label class="full">Deskripsi<input data-field="description" value="${esc(x.description||'')}"></label><label class="full">Foto<div class="file-row"><input type="file" accept="image/*" data-file>${x.image_url?`<img class="preview" src="${esc(x.image_url)}">`:''}</div></label><div class="actions"><button class="edit" onclick="saveEvent('${x.id}',this)">Simpan</button><button class="delete" onclick="removeRow('events','${x.id}',loadEvents)">Hapus</button></div></div>`}
window.saveEvent=async(id,btn)=>{try{const box=btn.closest('.card-editor'),v={};box.querySelectorAll('[data-field]').forEach(i=>v[i.dataset.field]=i.value);v.position=Number(v.position)||99;const f=box.querySelector('[data-file]').files[0];if(f)v.image_url=await upload(f);const {error}=await db.from('events').update(v).eq('id',id);if(error)throw error;toast('Event disimpan');loadEvents();}catch(e){toast(errMsg(e))}};
$('#addEvent').onclick=async()=>{const {error}=await db.from('events').insert({position:99,event_date:'',title:'Event Baru',time_location:'',description:''});if(error)toast(errMsg(error));else loadEvents();};
async function loadMemories(){const {data}=await db.from('memories').select('*').order('position');const box=$('#memoryList');box.innerHTML=(data||[]).map(x=>`<div class="card-editor"><label>Judul<input data-field="title" value="${esc(x.title)}"></label><label>Urutan<input type="number" data-field="position" value="${x.position}"></label><label class="full">Deskripsi<input data-field="description" value="${esc(x.description||'')}"></label><label class="full">Foto<div class="file-row"><input type="file" accept="image/*" data-file>${x.image_url?`<img class="preview" src="${esc(x.image_url)}">`:''}</div></label><div class="actions"><button class="edit" onclick="saveMemory('${x.id}',this)">Simpan</button><button class="delete" onclick="removeRow('memories','${x.id}',loadMemories)">Hapus</button></div></div>`).join('')||'<p>Belum ada album.</p>';}
window.saveMemory=async(id,btn)=>{try{const box=btn.closest('.card-editor'),v={};box.querySelectorAll('[data-field]').forEach(i=>v[i.dataset.field]=i.value);v.position=Number(v.position)||99;const f=box.querySelector('[data-file]').files[0];if(f)v.image_url=await upload(f);const {error}=await db.from('memories').update(v).eq('id',id);if(error)throw error;toast('Album disimpan');loadMemories();}catch(e){toast(errMsg(e))}};
$('#addMemory').onclick=async()=>{const {error}=await db.from('memories').insert({position:99,title:'Album Baru',description:''});if(error)toast(errMsg(error));else loadMemories();};
async function loadCorner(){const {data}=await db.from('corner').select('*').order('position');const box=$('#cornerList');box.innerHTML=(data||[]).map(x=>`<div class="card-editor"><label>Icon<input data-field="icon" value="${esc(x.icon||'✨')}"></label><label>Urutan<input type="number" data-field="position" value="${x.position}"></label><label>Judul<input data-field="title" value="${esc(x.title)}"></label><label class="full">Deskripsi<input data-field="description" value="${esc(x.description||'')}"></label><div class="actions"><button class="edit" onclick="saveSimple('corner','${x.id}',this,loadCorner)">Simpan</button><button class="delete" onclick="removeRow('corner','${x.id}',loadCorner)">Hapus</button></div></div>`).join('')||'<p>Belum ada item.</p>';}
window.saveSimple=async(table,id,btn,fn)=>{const box=btn.closest('.card-editor'),v={};box.querySelectorAll('[data-field]').forEach(i=>v[i.dataset.field]=i.value);v.position=Number(v.position)||99;const {error}=await db.from(table).update(v).eq('id',id);if(error)toast(errMsg(error));else{toast('Disimpan');fn();}};
$('#addCorner').onclick=async()=>{const {error}=await db.from('corner').insert({position:99,icon:'✨',title:'Item Baru',description:''});if(error)toast(errMsg(error));else loadCorner();};
init();
